import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * Represents a single Notification as returned by the API.
 *
 * Notifications are in-app or push messages generated by system events
 * (e.g. milestone completed, shipment status changed).
 */
export class NotificationResponseDto {
  @ApiProperty({
    description: 'Unique notification identifier (UUID)',
    example: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
  })
  id: string;

  @ApiProperty({
    description: 'UUID of the user this notification belongs to',
    example: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
  })
  userId: string;

  @ApiProperty({
    description: 'Short notification title',
    example: 'Milestone completed',
  })
  title: string;

  @ApiProperty({
    description: 'Full notification body',
    example: 'Customs clearance for SHP-2024-00123 has been completed.',
  })
  message: string;

  @ApiProperty({
    description: 'Notification category / type',
    example: 'MILESTONE_COMPLETED',
    enum: [
      'MILESTONE_COMPLETED',
      'SHIPMENT_STATUS_CHANGED',
      'PAYMENT_RELEASED',
      'DISPUTE_OPENED',
      'SYSTEM',
    ],
  })
  type: string;

  @ApiProperty({
    description: 'Whether the user has read this notification',
    example: false,
  })
  isRead: boolean;

  @ApiPropertyOptional({
    description: 'UUID of the related entity (shipment, milestone, etc.)',
    example: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    nullable: true,
  })
  relatedEntityId?: string | null;

  @ApiPropertyOptional({
    description: 'Type of the related entity',
    example: 'SHIPMENT',
    enum: ['SHIPMENT', 'MILESTONE', 'PAYMENT', null],
    nullable: true,
  })
  relatedEntityType?: string | null;

  @ApiProperty({
    description: 'ISO-8601 creation timestamp',
    example: '2024-03-22T14:00:00.000Z',
  })
  createdAt: string;

  @ApiPropertyOptional({
    description: 'ISO-8601 timestamp when the notification was read',
    example: '2024-03-22T15:30:00.000Z',
    nullable: true,
  })
  readAt?: string | null;
}